package GUI;

import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class JFReportes extends javax.swing.JFrame {

    OkHttpClient cliente;
    public JFReportes() {
        initComponents();
        cliente = new OkHttpClient();
    }
    public Response get(URL url)throws IOException {
            Request request = new Request.Builder()
                .url(url)
                .build();
            Response response = cliente.newCall(request).execute();
            return response;
    }//fin del metod consumir get
    public void graficar_matriz(){
         try{
            URL url  = new URL("http://192.168.0.18:5000/graficar_matriz");
            Response respuestas = get(url);
            File grafica = new File("C:\\Proyecto2\\grafica_matriz.dot");
            PrintWriter escribir = new PrintWriter(grafica);
            escribir.print(respuestas.body().string());
            escribir.close();
            Runtime.getRuntime().exec("CMD /C C:\\Grapvhiz\\bin\\dot -Tjpg C:\\Proyecto2\\grafica_matriz.dot -o C:\\Proyecto2\\grafica_matriz.jpg");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas al graficar la matriz");            
        }
    }
    public void graficar_usuarios(){
         try{
            URL url  = new URL("http://192.168.0.21:5000/usuarios");
            Response respuestas = get(url);
            File grafica = new File("C:\\Proyecto2\\grafica_usuarios.dot");
            PrintWriter escribir = new PrintWriter(grafica);
            escribir.print(respuestas.body().string());
            escribir.close();
            Runtime.getRuntime().exec("CMD /C C:\\Grapvhiz\\bin\\dot -Tjpg C:\\Proyecto2\\grafica_usuarios.dot -o C:\\Proyecto2\\grafica_usuarios.jpg");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas al graficar la matriz");            
        }
    }
    public void graficar_carpetas(){
        try{
            URL url  = new URL("http://192.168.0.21:5000/carpetas");
            Response respuestas = get(url);
            File grafica = new File("C:\\Proyecto2\\grafica_carpetas.dot");
            PrintWriter escribir = new PrintWriter(grafica);
            escribir.print(respuestas.body().string());
            escribir.close();
            Runtime.getRuntime().exec("CMD /C C:\\Grapvhiz\\bin\\dot -Tjpg C:\\Proyecto2\\grafica_carpetas.dot -o C:\\Proyecto2\\grafica_carpetas.jpg");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas al graficar la matriz");            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPReporte_Matriz = new javax.swing.JPanel();
        jBGraficar_Matriz = new javax.swing.JButton();
        lbl_matriz = new javax.swing.JLabel();
        jPReporte_Lista_Categorias = new javax.swing.JPanel();
        jBGraficar_Usuario = new javax.swing.JButton();
        lbl_usuarios = new javax.swing.JLabel();
        jPArbol_Remitentes = new javax.swing.JPanel();
        lbl_carpetas = new javax.swing.JLabel();
        jBGraficar_Carpetas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBGraficar_Matriz.setText("Graficar");
        jBGraficar_Matriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGraficar_MatrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPReporte_MatrizLayout = new javax.swing.GroupLayout(jPReporte_Matriz);
        jPReporte_Matriz.setLayout(jPReporte_MatrizLayout);
        jPReporte_MatrizLayout.setHorizontalGroup(
            jPReporte_MatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReporte_MatrizLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lbl_matriz, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(jBGraficar_Matriz)
                .addContainerGap())
        );
        jPReporte_MatrizLayout.setVerticalGroup(
            jPReporte_MatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReporte_MatrizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPReporte_MatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPReporte_MatrizLayout.createSequentialGroup()
                        .addComponent(jBGraficar_Matriz)
                        .addGap(0, 303, Short.MAX_VALUE))
                    .addComponent(lbl_matriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Reporte Matriz", jPReporte_Matriz);

        jBGraficar_Usuario.setText("Graficar");
        jBGraficar_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGraficar_UsuarioActionPerformed(evt);
            }
        });

        lbl_usuarios.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPReporte_Lista_CategoriasLayout = new javax.swing.GroupLayout(jPReporte_Lista_Categorias);
        jPReporte_Lista_Categorias.setLayout(jPReporte_Lista_CategoriasLayout);
        jPReporte_Lista_CategoriasLayout.setHorizontalGroup(
            jPReporte_Lista_CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReporte_Lista_CategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGraficar_Usuario)
                .addContainerGap())
        );
        jPReporte_Lista_CategoriasLayout.setVerticalGroup(
            jPReporte_Lista_CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReporte_Lista_CategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPReporte_Lista_CategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGraficar_Usuario))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reporte Usuarios", jPReporte_Lista_Categorias);

        lbl_carpetas.setBackground(new java.awt.Color(102, 102, 102));

        jBGraficar_Carpetas.setText("Graficar");
        jBGraficar_Carpetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGraficar_CarpetasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPArbol_RemitentesLayout = new javax.swing.GroupLayout(jPArbol_Remitentes);
        jPArbol_Remitentes.setLayout(jPArbol_RemitentesLayout);
        jPArbol_RemitentesLayout.setHorizontalGroup(
            jPArbol_RemitentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPArbol_RemitentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_carpetas, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGraficar_Carpetas)
                .addGap(4, 4, 4))
        );
        jPArbol_RemitentesLayout.setVerticalGroup(
            jPArbol_RemitentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPArbol_RemitentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPArbol_RemitentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_carpetas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGraficar_Carpetas))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Reporte Arbol B Carpetas", jPArbol_Remitentes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGraficar_MatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGraficar_MatrizActionPerformed
        graficar_matriz();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBGraficar_MatrizActionPerformed

    private void jBGraficar_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGraficar_UsuarioActionPerformed
        // TODO add your handling code here:
        graficar_usuarios();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon a = new ImageIcon("C:\\Proyecto2\\grafica_usuarios.jpg");
        Icon i = new ImageIcon(a.getImage().getScaledInstance(lbl_usuarios.getWidth(), lbl_usuarios.getHeight(), Image.SCALE_DEFAULT) );
        lbl_usuarios.setIcon(i);
        this.repaint();
    }//GEN-LAST:event_jBGraficar_UsuarioActionPerformed

    private void jBGraficar_CarpetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGraficar_CarpetasActionPerformed
        // TODO add your handling code here:
        graficar_carpetas();
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(JFReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon a = new ImageIcon("C:\\Proyecto2\\grafica_carpetas.jpg");
        Icon i = new ImageIcon(a.getImage().getScaledInstance(lbl_carpetas.getWidth(), lbl_carpetas.getHeight(), Image.SCALE_DEFAULT) );
        lbl_carpetas.setIcon(i);
        this.repaint();
    }//GEN-LAST:event_jBGraficar_CarpetasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGraficar_Carpetas;
    private javax.swing.JButton jBGraficar_Matriz;
    private javax.swing.JButton jBGraficar_Usuario;
    private javax.swing.JPanel jPArbol_Remitentes;
    private javax.swing.JPanel jPReporte_Lista_Categorias;
    private javax.swing.JPanel jPReporte_Matriz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_carpetas;
    private javax.swing.JLabel lbl_matriz;
    private javax.swing.JLabel lbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
